# -*- coding: utf-8 -*-
"""
param_help.py
-------------
GUI 中每个关键参数的“中文解释”。
"""
HELP = {
    "T_path": "相机到机床的外参（R、t、T），单位毫米。来源：手眼标定。",
    "gcode_path": "需要对齐/纠偏的理论 G 代码文件路径。支持 G0/G1 直线与 G2/G3 圆弧（会自动重采样为折线）。",
    "pixel_size_mm": "顶视投影的分辨率（每像素代表的毫米数）。数值越小，分辨率越高，但处理时间和内存占用会增大。",
    "bounds_qlo": "用于估计 ROI 外接边界时的下分位数（%）。",
    "bounds_qhi": "用于估计 ROI 外接边界时的上分位数（%）。",
    "bounds_margin_mm": "在分位数边界基础上向外扩展的冗余量（mm），避免裁剪掉边缘数据。",
    "max_grid_pixels": "顶视图允许的最大像素数（宽×高），用于自动调整 pixel_size_mm，防止显存/内存占用过高。",
    "roi_mode": "ROI 选取方式：camera_rect=相机像素矩形；machine=机床坐标轴对齐正方形；gcode_bounds=以 G 代码包围盒自动选区；none=不裁剪。",
    "cam_roi_xywh": "当 roi_mode=camera_rect 时生效，（x,y,w,h）为相机像素坐标的矩形框。",
    "roi_center_xy": "当 roi_mode=machine 时生效，机床坐标系下 ROI 的中心（mm）。",
    "roi_size_mm": "当 roi_mode=machine 时生效，ROI 的边长（mm）。",
    "z_select": "在“展平后的残差高度图”上选择最近层的准则：max=最高层；min=最低层。",
    "nearest_use_percentile": "抽取最近层时是否用分位数阈值（True 更稳健），否者按绝对阈值。",
    "nearest_qlo": "最近层采用分位数阈值的下界（%）。",
    "nearest_qhi": "最近层采用分位数阈值的上界（%）。",
    "depth_margin_mm": "最近层厚度（mm，作用在残差高度域）。",
    "morph_open": "形态学开运算核大小（像素），用于去除小噪声孔洞。0 代表关闭。",
    "morph_close": "形态学闭运算核大小（像素），用于填充小孔洞。0 代表关闭。",
    "min_component_area_px": "连通域最小面积（像素），小于该阈值的区域将被移除。",
    "plane_enable": "是否启用 ROI 内 RANSAC 平面拟合与展平（建议开启）。",
    "plane_ransac_thresh_mm": "RANSAC 平面内点阈值（mm），越小要求越严格。",
    "plane_ransac_iters": "RANSAC 迭代次数。",
    "plane_sample_cap": "RANSAC 时用于拟合的最大采样点数（随机下采样），防止过慢。",
    "plane_min_inlier_ratio": "平面内点比例的质量门槛（仅用于运行时的告警/判断）。",
    "rdp_epsilon_px": "骨架折线压缩（Ramer–Douglas–Peucker）阈值（像素）。",
    "resample_step_px": "骨架折线重采样的步长（像素）。",
    "guide_enable": "是否启用“G 代码引导的中心线拟合”流程；关闭时直接使用骨架。",
    "guide_step_mm": "将原始 G 代码重采样为该步长（mm）。值越小曲线越细致。",
    "guide_halfwidth_mm": "在每个 G 代码点的法向上做±半宽的扫描以寻找中心线，单位 mm。",
    "guide_use_dt": "法向扫描时是否使用距离变换（DT）进行峰值检测。",
    "guide_min_on_count": "法向扫描沿线能检测到“在最近层内”的最少采样点数，低于则视作该处无效。",
    "guide_smooth_win": "对偏移序列进行移动平均的窗口大小（点数，奇数），用于抑制抖动。",
    "guide_max_offset_mm": "偏移限幅（mm），超过此绝对值会被裁剪。",
    "guide_min_valid_ratio": "引导拟合成功的最低有效比例，低于该值会回退到骨架。",
    "guide_fallback_to_skeleton": "当引导拟合失败时是否回退到骨架。",
    "arrow_stride": "在可视化图中绘制偏差箭头的步长（每隔多少个点画一次）。",
    "draw_normal_probes": "可视化时是否绘制法向采样线（调试用）。",
    "ema_alpha": "在线 EMA 纠偏的平滑系数（0~1），越大响应越快。",
    "deadband_mm": "在线纠偏的死区（mm），小于该幅度的偏移被抑制。",
    "clip_mm": "在线纠偏的中位向量裁剪阈值（mm）。",
    "max_step_mm": "每帧允许的最大位移步长（mm），防止过快运动。",
    "export_on_key": "原程序里按键触发导出的键位，GUI 中不使用。",
    "out_dir": "输出目录（用于保存 offset_table.csv、corrected.gcode、quicklook.png 等）。",
    "offset_csv": "偏差表 CSV 输出路径。",
    "corrected_gcode": "纠偏后 G 代码输出路径。",
    "offset_apply_mode": "纠偏应用策略：invert=朝向理论轨迹纠偏（默认）；follow=直接沿着测得中心线（同向）。",
    "centerline_gcode": "可选：把检测到的中心线直接另存为 G 代码的路径。",
    "export_centerline": "若为 True，则同时导出中心线轨迹。",
    "auto_flip_offset": "自动检测并翻转“测得偏移”的符号（通过中心线与原轨迹的 Y 中位差进行对比）。",
    "preview_corrected": "导出时在可视化窗口叠加黄色的 corrected 预览。",
    "save_corrected_preview": "是否把预览另存为 PNG。",
    "Guard": "质量门槛设置（有效比例/偏差 P95/平面内点率），仅用于运行确认与告警。"
}
